name: 'Gemini PR Reviewer'

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: 'read'
  pull-requests: 'write'

jobs:
  review-pr:
    if: github.event_name == 'pull_request' || (github.event.issue.pull_request && contains(github.event.comment.body, '@gemini-cli /review'))
    runs-on: 'ubuntu-latest'
    steps:
      # Step 1: Check out the code from the PR branch
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0 # Fetches full history to allow diffing

      # Step 2a: Calculate diff on pull_request event
      - name: 'Calculate diff on pull_request'
        id: 'diff_pr'
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git diff --no-color origin/${{ github.event.pull_request.base.ref }} > diff.txt || true
          {
            echo 'diff_output<<EOF'
            cat diff.txt
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      # Step 2b: Calculate diff on issue_comment event
      - name: 'Calculate diff on comment'
        id: 'diff_comment'
        if: github.event_name == 'issue_comment'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BASE_REF=$(gh pr view ${{ github.event.issue.number }} --json baseRefName -q .baseRefName)
          git fetch origin $BASE_REF
          git diff --no-color origin/$BASE_REF > diff.txt || true
          {
            echo 'diff_output<<EOF'
            cat diff.txt
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      # Step 3: Run Gemini CLI with the diff as input
      - name: 'Run Gemini Review'
        id: 'gemini'
        uses: 'google-github-actions/run-gemini-cli@main'
        with:
          gemini_api_key: '${{ secrets.GEMINI_API_KEY }}'
          prompt: |
            You are an expert Google engineer performing a code review.
            Your goal is to provide a concise, helpful summary of the following code changes.
            Identify any potential issues, bugs, or areas for improvement in this Python/Flask project.
            Provide specific code suggestions for improvement if you find any.

            Here is the diff of the changes:
            ```diff
            ${{ steps.diff_pr.outputs.diff_output || steps.diff_comment.outputs.diff_output }}
            ```

      # Step 4: Post the review as a comment on the PR
      - name: 'Comment on PR'
        uses: 'actions/github-script@v7'
        env:
          SUMMARY: ${{ steps.gemini.outputs.summary }}
        with:
          script: |
            const summary = process.env.SUMMARY;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🤖 Gemini PR Review\n\n${summary}`
            })
