name: 'Gemini PR Reviewer'

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - name: Gemini PR Reviewer
        uses: google-github-actions/run-gemini-cli@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: 'You are a Google engineer performing a code review. Given the following diff, please summarize the changes and identify any potential issues or areas for improvement.'
          diff: ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          comment: true
